program = "fraktaler-3"
version = "2-167-g0ccd6ff"
location.real = "0.58602938444037209377518962547290397109748245837"
location.imag = "0.476123093672008792332965447964703798686092013023"
location.zoom = "1.2e36"
bailout.iterations = 1048576
bailout.maximum_reference_iterations = 1048576
bailout.maximum_perturb_iterations = 65536
bailout.maximum_bla_steps = 65536
bailout.escape_radius = 4.0
image.width = 960
image.height = 540
image.subframes = 4
transform.rotate = -58.2363
transform.stretch_angle = 40.8756
transform.stretch_amount = 268.693

[[formula]]
power = 3
abs_y = true
abs_x = true
[[formula]]
power = 3



[colour]
shader = """
uniform float speed;
uniform float offset;
uniform float gamma;
uniform float exposure;
uniform vec3 interior;

vec3 colour(void)
{
  // FIXME hue loses precision at higher iteration counts
  float h = (float(getN0()) + getNF()) / exp2(speed);
  float s = getT() > 0.0 ? 0.4 : 0.6;
  float v = 0.25 + 0.25 * log2(length(getDE()));
  h -= floor(h);
  v += offset;
  v = clamp(v, 0.0, 1.0);
  vec3 rgb = hsv2rgb(vec3(h, s, v));
  if (length(getDE()) <= 0.0)
  {
    rgb = interior;
  }
  rgb = pow(rgb, vec3(1.0 / gamma));
  rgb *= exp2(exposure);
  rgb = clamp(rgb, vec3(0.0), vec3(1.0));
  return rgb;
}
\
"""

[[colour.uniforms]]
value = 2.0
type = "float"
name = "exposure"
index = 0
component = 0
[[colour.uniforms]]
value = 1.5
type = "float"
name = "gamma"
index = 0
component = 0
[[colour.uniforms]]
value = 0.0
type = "float"
name = "interior"
index = 0
component = 0
[[colour.uniforms]]
value = 0.0
type = "float"
name = "interior"
index = 0
component = 1
[[colour.uniforms]]
value = 0.0
type = "float"
name = "interior"
index = 0
component = 2
[[colour.uniforms]]
value = 1.0
type = "float"
name = "offset"
index = 0
component = 0
[[colour.uniforms]]
value = 17.5
type = "float"
name = "speed"
index = 0
component = 0

[colour.background]
r = 0.5
g = 0.5
b = 0.5

