#!/usr/bin/env bash
# Build a GUI-free Fraktaler-3 *batch* binary on Linux for the harness.
#
# Why this script exists
# ----------------------
# The repo vendors F3 3.1 source under `fraktaler-3-3.1/fraktaler-3-3.1/` and
# commits the macOS batch binaries (`*.macos`), but the Linux binary is
# gitignored (`.gitignore`: `/fraktaler-3-3.1/*.linux`) — it is meant to be
# built per-machine. `scripts/compare_f3.py` / `scripts/harness.py` auto-detect
# `fraktaler-3-3.1/fraktaler-3-3.1.linux` (preferred on Linux), so this script
# produces exactly that path. Without it, speed + parity axes are dark on Linux
# (a macOS arm64 binary cannot run here).
#
# The upstream Makefile builds the full GUI app (SDL2 + imgui + implot + clew),
# whose submodules are absent here. The harness only needs F3 **batch** mode
# with raw N0/NF EXR channels (`render.exr_channels = ["N0","NF"]`), which goes
# through `batch()` in `src/main.cc` and never touches the GUI. So we compile
# the core translation units GUI-free (no HAVE_GUI / HAVE_CL / HAVE_ICON) and
# provide a tiny shim for the two symbols that otherwise live in `gui.cc`
# (`gui()` — never called in raw-EXR batch — and `newton_relative_start`) plus
# `colour_default_glsl` (guarded by HAVE_GUI in `colour.cc`, but referenced
# unconditionally by `param.cc`).
#
# Idempotent: re-running rebuilds from scratch. The vendored F3 source tree is
# left pristine — all generated scaffolding and objects live in a gitignored
# build dir.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
F3="$REPO/fraktaler-3-3.1/fraktaler-3-3.1"
SRC="$F3/src"
BUILD="$REPO/fraktaler-3-3.1/build-linux-batch"
OUT="$REPO/fraktaler-3-3.1/fraktaler-3-3.1.linux"

if [ ! -d "$SRC" ]; then
  echo "error: F3 source not found at $SRC" >&2
  exit 1
fi

# --- native dependencies (Debian/Ubuntu) ---------------------------------
# libpng/zlib are usually present; the rest are the F3 batch requirements.
DEPS="libgmp-dev libmpfr-dev libmpc-dev libmpfrc++-dev libopenexr-dev \
      libglm-dev libjpeg-dev libdeflate-dev libsdl2-dev libpng-dev zlib1g-dev \
      libtoml11-dev"
if [ "${SKIP_APT:-0}" != "1" ]; then
  if command -v apt-get >/dev/null 2>&1; then
    echo "== installing native deps (set SKIP_APT=1 to skip) =="
    apt-get install -y --no-install-recommends $DEPS || {
      echo "apt-get failed; retrying after update" >&2
      apt-get update && apt-get install -y --no-install-recommends $DEPS
    }
  else
    echo "warning: apt-get not found — assuming deps are already present" >&2
  fi
fi

# --- generated scaffolding (kept out of the vendored tree) ----------------
rm -rf "$BUILD"
mkdir -p "$BUILD"

# Empty embedded-source archive header (only used by `--source`, not batch).
cat > "$BUILD/fraktaler-3-source.7z.h" <<'EOF'
const unsigned char fraktaler_3_source_7z[] = {0x00};
const unsigned int fraktaler_3_source_7z_len = 0;
EOF

# Shim for symbols normally defined in gui.cc / colour.cc (under HAVE_GUI).
python3 - "$F3/examples/default.glsl" "$BUILD/stub_gui.cc" <<'PY'
import sys
glsl = open(sys.argv[1], "rb").read().decode("utf-8", "replace")
delim = "F3GLSL"
open(sys.argv[2], "w").write(
    '// GUI-free batch build shim (generated by scripts/build_f3_linux.sh).\n'
    '// Provides the handful of symbols that live in gui.cc / colour.cc under\n'
    '// HAVE_GUI but are referenced by the batch path.\n'
    '#include <cstdio>\n#include <string>\n#include "main.h"\n#include "floatexp.h"\n\n'
    'int gui(const char *, const char *, bool)\n{\n'
    '  std::fprintf(stderr, "fraktaler-3: built without GUI (batch-only)\\n");\n'
    '  return 1;\n}\n\n'
    '// Newton relative-start zoom (1 => formula evaluates as absolute).\n'
    'floatexp<float, int> newton_relative_start = 1;\n\n'
    '// Default colour shader (from examples/default.glsl); unused for raw EXR.\n'
    'const char *colour_default_glsl = R"%s(%s)%s";\n' % (delim, glsl, delim)
)
PY

# --- compile + link -------------------------------------------------------
CF="-std=c++17 -O2 -march=native -DHAVE_EXR=3 -DHAVE_FS -DTOML11_API=3 -DHAVE_FLOAT128 -DMPFR_WANT_FLOAT128"
VER='-DFRAKTALER_3_VERSION_STRING="\"3.1-batch\"" -DIMGUI_GIT_VERSION_STRING="\"none\"" -DIMGUI_FILEBROWSER_GIT_VERSION_STRING="\"none\"" -DIMPLOT_GIT_VERSION_STRING="\"none\"" -DCLEW_GIT_VERSION_STRING="\"none\""'
PKGCF="$(pkg-config --cflags libpng mpfr zlib OpenEXR sdl2)"
PKGLIBS="$(pkg-config --libs libpng mpfr zlib OpenEXR sdl2)"

# Core batch TUs — everything except GUI/GL/OpenCL sources.
CORE="batch bla colour engine hybrid image_raw image_rgb jpeg main param \
      png render source version wisdom"

echo "== compiling F3 batch TUs =="
for s in $CORE; do
  # shellcheck disable=SC2086
  g++ $CF $VER $PKGCF -I"$SRC" -I"$BUILD" -c "$SRC/$s.cc" -o "$BUILD/$s.o"
done
# shellcheck disable=SC2086
g++ $CF $VER $PKGCF -I"$SRC" -I"$BUILD" -c "$BUILD/stub_gui.cc" -o "$BUILD/stub_gui.o"

echo "== linking $OUT =="
# shellcheck disable=SC2086
g++ -O2 -march=native -o "$OUT" "$BUILD"/*.o \
  $PKGLIBS -lstdc++ -lstdc++fs -lm -lquadmath -lmpc -ldl -ljpeg -ldeflate
strip --strip-unneeded "$OUT" 2>/dev/null || true

echo "== done: $OUT =="
"$OUT" --version 2>&1 | head -1
